# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='username',
        ),
    ]
