# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20170818_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AddField(
            model_name='users',
            name='datehired',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
