# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20170818_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='datehired',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
