# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_item', to='first.Users'),
            preserve_default=False,
        ),
    ]
